import os
from subprocess import call

top = '..' 
out = '.' 

def options(opt):
        opt.load('compiler_cxx waf_unit_test')
        
def configure(conf):
        conf.load('compiler_cxx waf_unit_test')

def build(bld):
        bld(features='cxx cxxprogram test', 
                source='TestPhoton.cpp', 
                # source = bld.path.ant_glob('**/Source/*.C')
                target='TestPhoton', 
                name='TestPhoton',
                includes=['.', '..'], 
                lib=['gtest'], 
                use=['GTEST', 'PTHREAD', 'photon', 'algebra'])

        bld(features='cxx cxxprogram test', 
                source='TestScene.cpp', 
                target='TestScene', 
                name='TestScene',
                includes=['.', '..'], 
                lib=['gtest'], 
                use=['GTEST', 
                        'PTHREAD', 
                        'photon', 
                        'algebra', 
                        'scene'])

        from waflib.Tools import waf_unit_test
        bld.add_post_fun(waf_unit_test.summary)

